version: 2

sources:
  - name: banking_raw
    project: project-b3789463-f591-4856-839
    dataset: banking_raw
    tables:
      - name: accounts
        columns:
          - name: account_id
            tests:
              - unique
              - not_null
      - name: cards
        columns:
          - name: card_id
            tests:
              - unique
              - not_null
      - name: transactions
        columns:
          - name: transaction_id
            tests:
              - unique
              - not_null